### ISSUE TITLE
Add an Environment variable to adjust time zone?

### ISSUE THREAD

**Issue by byujiang** [docker-library/postgres#866] opened 2021-07-12 07:52 UTC
Hi, there,

The default time zone is UTC 0, while for people at different timezone, it may be a little confusing and inconvenient. So is it possible to providing an environment variable to adjust the default timezone to specific timezone like `-e TZ=Asia/Shanghai` ?

**Comment by wglambert** [comment] 2021-07-12 16:23
`-e TZ=Asia/Shanghai` works just fine
Duplicate of https://github.com/docker-library/postgres/issues/732#issuecomment-628039882 https://github.com/docker-library/postgres/issues/641#issuecomment-558333174 https://github.com/docker-library/postgres/issues/610#issuecomment-533616603

```console
$ docker run -d --rm -e TZ=Asia/Shanghai -e POSTGRES_PASSWORD=pass --name postgres postgres
0cc5ecb024c9b302c771066ddf9c10173c626c3bf738744ba94babccf415e200

$ docker exec -it postgres psql -U postgres
psql (13.3 (Debian 13.3-1.pgdg100+1))
Type "help" for help.

postgres=# show timezone;
   TimeZone
---------------
 Asia/Shanghai
(1 row)
```

**Closed** 2021-07-12 19:07 UTC
Labels: question
