### ISSUE TITLE
when I build images from Dockerfile--11,it's failed

### ISSUE THREAD

**Issue by liyin37** [docker-library/postgres#687] opened 2020-02-18 02:08 UTC
the error is :
+ sed -ri s/#(create_main_cluster) .*$/\1 = false/ /etc/postgresql-common/createcluster.conf
+ apt-get install -y postgresql-11=11.6-1.pgdg90+1
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '11.6-1.pgdg90+1' for 'postgresql-11' was not found

please help check it

**Comment by liyin37** [comment] 2020-02-18 02:15
then,I try other version,it's have the same error,like version Dockerfile-10
+ sed -ri s/#(create_main_cluster) .*$/\1 = false/ /etc/postgresql-common/createcluster.conf
+ apt-get install -y postgresql-10=10.11-1.pgdg90+1
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '10.11-1.pgdg90+1' for 'postgresql-10' was not found

**Comment by wglambert** [comment] 2020-02-18 18:45
https://github.com/docker-library/postgres/issues/678#issuecomment-586403467

Duplicate of https://github.com/docker-library/postgres/issues/677

**Comment by liyin37** [comment] 2020-02-19 02:03
but my system is CentOS7.6 , How to do

**Comment by yosifkit** [comment] 2020-02-19 21:28
If you want to `docker build` it, you need to use the newest version of the Dockerfile. Upstream has updated their apt repo and it only contains the latest of each release (which the Dockerfiles have been updated to use):

https://github.com/docker-library/postgres/blob/4dc16e44d16480d9c8e5eb705c15468d65366e43/10/Dockerfile#L78
https://github.com/docker-library/postgres/blob/4dc16e44d16480d9c8e5eb705c15468d65366e43/11/Dockerfile#L78

**Closed by yosifkit** 2020-02-19 21:28 UTC
Labels: question
