### ISSUE TITLE
Upgrade from postgres:11.5-alpine to postgres:12.0-alpine

### ISSUE THREAD

**Issue by micemuni** [docker-library/postgres#618] opened 2019-10-16 08:40 UTC
Hi Team,
I would like to upgrade the postgres 11.5 to 12 version with out losing data.
So please let me know the steps OR scripts OR procedures to upgrade postgres version 

Thank you in advance

**Comment by wglambert** [comment] 2019-10-16 16:32
Tianon has a repo with upgrade-containers to invoke [pg_upgrade](https://www.postgresql.org/docs/11/upgrading.html#UPGRADING-VIA-PG-UPGRADE) 
https://github.com/tianon/docker-postgres-upgrade
Postgres [documentation](https://www.postgresql.org/docs/11/upgrading.html#UPGRADING-VIA-PG-UPGRADE) on `pg_upgrade`

https://github.com/docker-library/postgres/issues/37#issuecomment-404598989
>There actually is support for migrating data files in PostgreSQL, it's called [pg_upgrade](https://www.postgresql.org/docs/current/static/pgupgrade.html). The Docker container is special in that it's difficult to use this support because it needs both the older and the newer versions installed on the same system. The Docker container isn't set up to work this way. Alternately, you can also look into replication if you have large data sets or absolutely can't have any downtime. Options are actually discussed on this [official documentation page](https://www.postgresql.org/docs/current/static/upgrading.html).

Closing as a duplicate of #37

**Closed by wglambert** 2019-10-16 16:32 UTC
Labels: question

**Comment by micemuni** [comment] 2019-10-23 09:24
Hi Team,
I am using docker & currently running 11.5-alpine postgres
I would like to upgrade to 12.0-alpine postgres. But If i use this "https://github.com/tianon/docker-postgres-upgrade" then i got error, because 11.5 / 12.0 version folder is not there. It's 11 /12 folder only.

Please help me how to upgrade in this case.
Thank you in advance

**Comment by micemuni** [comment] 2019-10-23 09:24
@wglambert  Please suggest to proceed.
