### ISSUE TITLE
Cannot start instance on custom port (with -p <port>) if another instance running on 5432

### ISSUE THREAD

**Issue by lpfeup** [docker-library/postgres#398] opened 2018-01-10 20:20 UTC
Both instances start correctly with the following docker-compose.yml (both use non-default port):

```
version: '2'
services:
  postgres1:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example1
    net: host
    command: -p 5434
  postgres2:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example2
    net: host
    command: -p 5435
```` 

The following does not work if postgres1 is started before postgres2:

```
version: '2'
services:
  postgres1:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example1
    net: host
    command: -p 5432
  postgres2:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example2
    net: host
    command: -p 5435
```` 

Output from postgres2:

```
[34] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
[34] LOG:  could not bind IPv4 address "127.0.0.1": Address in use
[34] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
[34] WARNING:  could not create listen socket for "localhost"
[34] FATAL:  could not create any TCP/IP sockets
```

**Comment by lpfeup** [comment] 2018-01-10 20:47
This seems to be an issue with pg_ctl on `docker_entrypoint.sh` not knowing of the port parameter.
If instead of using `command: -p <port>`, I use the `PGPORT` environment variable, everything works as it should:

```
version: '2'
services:
  postgres1:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example1
      PGPORT: 5432
    net: host
  postgres2:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example2
      PGPORT: 5435
    net: host
````

**Comment by yosifkit** [comment] 2018-01-10 21:32
That is one solution to use `PGPORT`. We are considering passing the command args to the `pg_ctl` temporary postgres server used for initialization so that your earlier version would work. Do you really need to run them as net host on the same machine?  You can accomplish the same thing with [port mapping](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/#connect-using-network-port-mapping).

Closing as solved with `PGPORT` and duplicate of https://github.com/docker-library/postgres/issues/196.

**Closed by yosifkit** 2018-01-10 21:32 UTC
