### ISSUE TITLE
10.alpine Initialization randomly freezes

### ISSUE THREAD

**Issue by archerabi** [docker-library/postgres#656] opened 2019-12-20 02:12 UTC
In our CI pipeline, we run some sql scripts on initialization of the postgres container. This works well most of the time.
When there is heavy load on our CI cluster, we are noticing that the initialization scripts executes all of our sql but doesn't restart postgres. 

**Successful**
```
2019-12-19 22:55:54.524 UTC [114] STATEMENT:  INSERT INTO tag (account_id, created_at)
	SELECT NULL, NOW();
INSERT 0 0
waiting for server to shut down....2019-12-19 22:55:54.559 UTC [34] LOG:  received fast shutdown request
2019-12-19 22:55:54.571 UTC [34] LOG:  aborting any active transactions
2019-12-19 22:55:54.572 UTC [34] LOG:  worker process: logical replication launcher (PID 41) exited with exit code 1
2019-12-19 22:55:54.572 UTC [36] LOG:  shutting down
2019-12-19 22:55:54.970 UTC [34] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.
```

**Unsuccessful ( postgres doesn't restart and is killed after a timeout. Notice diff in timestamps)**
```
2019-12-19 22:55:54.524 UTC [114] STATEMENT:  NSERT INTO tag (account_id, created_at)
	SELECT NULL, NOW();
INSERT 0 0

waiting for server to shut down....2019-12-19 23:03:37.362 UTC [34] LOG:  received fast shutdown request
2019-12-19 23:03:37.364 UTC [34] LOG:  aborting any active transactions
2019-12-19 23:03:37.365 UTC [34] LOG:  worker process: logical replication launcher (PID 41) exited with exit code 1
2019-12-19 23:03:37.366 UTC [36] LOG:  shutting down
```

Is it possible `pg_ctl` in `docker_temp_server_stop` does not return ?  

**Dockerfile**
```
FROM postgres:10.10-alpine
ENV DIR=/docker-entrypoint-initdb.d/ SEED_DIR=/etc/postgresql/seed/ SCRIPTS_DIR=/etc/postgresql/scripts/
RUN mkdir -p ${DIR} && mkdir -p ${SEED_DIR}

COPY postgresql.conf ${SCRIPTS_DIR}/postgresql.conf
COPY scripts/ ${SCRIPTS_DIR}
COPY seed/*.sql ${SEED_DIR}
COPY initialize.sh ${DIR}/

RUN chown -R postgres: ${SCRIPTS_DIR} && chown -R postgres: ${SEED_DIR} && chown postgres: ${DIR}/initialize.sh

ARG COMMIT
ENV COMMIT $COMMIT
```

**Comment by yosifkit** [comment] 2019-12-20 23:10
> Is it possible `pg_ctl` in `docker_temp_server_stop` does not return ?

Maybe.  If the system is overloaded and postgres is still trying to shut down, then it makes sense that `pg_ctl` is still waiting for it to exit (so, working as designed?).

----

On a side note, you may want to use `--chown postgres:postgres` on your `COPY` lines so that the files are not duplicated in the docker layers. (i.e. ensure any file/folder has the proper ownership in the layer in which it is created).

**Comment by wglambert** [comment] 2020-01-06 18:24
Not under load I don't see an issue with `pg_ctl stop`

```console
$ docker run -d --rm --name postgres postgres:10.10-alpine
33bf1395dcb610401fcf0877344fe58d52b5398422afc139cd798ee565e1fe69

$ docker exec -it postgres sh
/ # pg_ctl
pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.

/ # su postgres
/ $ pg_ctl stop
waiting for server to shut down....

$ docker exec -it postgres sh
Error: No such container: postgres
```

**Comment by archerabi** [comment] 2020-01-06 18:51
Thank you for your responses. I haven't been able to reproduce this on my machine. Seems to only happen on our CI cluster. For now we've got around it by adding retries and waits in our application. Seems like the container eventually starts up, but sometimes takes > 3 minutes.

**Comment by yosifkit** [comment] 2020-02-10 23:40
Since we are unable to reproduce, we will close the issue.

**Closed by yosifkit** 2020-02-10 23:40 UTC
Labels: question
