### ISSUE TITLE
error: postgres:9.6-alpine - exited with code 127

### ISSUE THREAD

**Issue by ekelvin** [docker-library/postgres#365] opened 2017-11-02 16:01 UTC
If you use the online image: postgres:9.6-alpine
it works fine but if I use the dockerfile with the entry point it exits with code 127
```
...
': No such file or directoryute 'bash
cms_posgres_1 exited with code 127
```

**Comment by yosifkit** [comment] 2017-11-02 18:35
Looks like a duplicate of #347.

**Closed** 2017-11-02 21:11 UTC
