### ISSUE TITLE
postgres container with external volume erases database

### ISSUE THREAD

**Issue by AgentCormac** [docker-library/postgres#169] opened 2016-06-19 22:25 UTC
Hi. How do I externalise a database from within this container? Starting the container with no docker volume is fine. Starting the container with a docker volume mapped to a host folder erases the database and config. I understand that this is correct docker volume!e behaviour, the host folder is mounted over the top of the container folder. 
How to I get around this issue and map the db that is created on container start up to my host folder so that it is available when the container next starts up?

Not sure what I am doing wrong here.  

```
docker run --name test-postgres \
-e POSTGRES_PASSWORD=test123 \
-v /home/vagrant/workspace/shared-data/postgres:/var/lib/postgresql \
-d postgres:9.6
```

This spins up the container and cretes the DB as expected. Container result:  
    root@fe0e5751c98d:/var/lib/postgresql# ls -al data
    total 0
    drwxr-xr-x. 2 root     root      6 Jun 20 12:32 .
    drwxr-xr-x. 3 postgres postgres 17 Jun 20 12:32 ..           

The mapped drive on the host has the data folder created but it is empty!
    [vagrant@localhost postgres]$ ls -al
    total 1
    drwxrwxrwx. 1 vagrant vagrant 0 Jun 20 12:27 .
    drwxrwxrwx. 1 vagrant vagrant 0 Jun 18 09:33 ..
    -rwxrwxrwx. 1 vagrant vagrant 5 Jun 19 21:47 container.txt
    drwxrwxrwx. 1 vagrant vagrant 0 Jun 20 12:27 data
    -rwxrwxrwx. 1 vagrant vagrant 0 Jun 20 12:24 dockerhost.txt
    [vagrant@localhost postgres]$ ls -al data
    total 0
    drwxrwxrwx. 1 vagrant vagrant 0 Jun 20 12:27 .
    drwxrwxrwx. 1 vagrant vagrant 0 Jun 20 12:27 ..

Spotted that the directories created by the postgres container (when not mapping to a Vagrant shared folder) on the docker host have odd permissions (owners and group).

```
[vagrant@localhost ~]$ ls -al
total 20
drwx------. 4 vagrant vagrant 4096 Jun 23 17:51 .
drwxr-xr-x. 3 root    root      20 May 21 20:07 ..
-rw-r--r--. 1 vagrant vagrant   18 Nov 20  2015 .bash_logout
-rw-r--r--. 1 vagrant vagrant  193 Nov 20  2015 .bash_profile
-rw-r--r--. 1 vagrant vagrant  231 Nov 20  2015 .bashrc
drwx------. 2 vagrant root      28 Jun 23 17:47 .ssh
-rw-r--r--. 1 vagrant vagrant    6 May 21 13:07 .vbox_version
drwxr-xr-x. 4 vagrant vagrant   39 Jun 23 18:01 workspace
[vagrant@localhost ~]$ ls -al workspace/
total 4
drwxr-xr-x. 4 vagrant vagrant   39 Jun 23 18:01 .
drwx------. 4 vagrant vagrant 4096 Jun 23 17:51 ..
drwxr-xr-x. 3 root    root      17 Jun 23 18:01 postgres
drwxr-xr-x. 5 vagrant vagrant   46 Jun 23 17:51 shared-data
[vagrant@localhost ~]$ ls -al workspace/postgres/
total 4
drwxr-xr-x.  3 root              root      17 Jun 23 18:01 .
drwxr-xr-x.  4 vagrant           vagrant   39 Jun 23 18:01 ..
drwx------. 19 systemd-bus-proxy root    4096 Jun 23 18:01 data
[vagrant@localhost ~]$ ls -al workspace/postgres/data
ls: cannot open directory workspace/postgres/data: Permission denied
[vagrant@localhost ~]$ sudo ls -al workspace/postgres/data
```

The postgres data directory has been created by systemd-bus-proxy. Could the group and owner of the container created folder be preventing the folder from being mapped correctly by Docker or Vagrant??

**Comment by deinspanjer** [comment] 2016-06-21 19:18
Just a quick idea, did you try specifying the full path that is used in the VOLUME directive, /var/lib/postgresql/data ?

**Comment by pydolan** [comment] 2016-06-22 15:50
Just tested with full path (/var/lib/postgresql/data), and this fixes the missing data issue for me. 

It seems that when the parent path is used (/var/lib/postgresql) as the named volume with Docker (currently on v1.11), this data disappearance happens. I don't think the Postgres container is doing anything wrong, but maybe worth inquiring with Docker directly?  (Note that the unnamed volume -- the one declared in Postgres's Dockerfile is still created.. I forget which of the two volumes has data though; maybe OP can verify).

**Comment by AgentCormac** [comment] 2016-06-23 18:56
Hmm. spotted something interesting with the permissions on the posgres directories that get created on the dockerhost. See above.

**Comment by yosifkit** [comment] 2018-05-18 20:32
Duplicate of #103; see specifically https://github.com/docker-library/postgres/issues/103#issuecomment-167631548

**Closed by yosifkit** 2018-05-18 20:32 UTC
Labels: Issue
