### ISSUE TITLE
trying to build 9.4 I get : Version '9.4.4-1.pgdg80+1' for 'postgresql-9.4' was not found

### ISSUE THREAD

**Issue by danwyry** [docker-library/postgres#96] opened 2015-10-08 16:21 UTC
when I run docker-compose build it breaks with this error message: 

E: Version '9.4.4-1.pgdg80+1' for 'postgresql-9.4' was not found
E: Version '9.4.4-1.pgdg80+1' for 'postgresql-contrib-9.4' was not found
Service 'pg' failed to build: The command '/bin/sh -c apt-get update 	&& apt-get install -y postgresql-common 	&& sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf 	&& apt-get install -y 		postgresql-$PG_MAJOR=$PG_VERSION 		postgresql-contrib-$PG_MAJOR=$PG_VERSION 	&& rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

y remove the =$PG_VERSION part from the script in my personal repo and worked ok, but still, this seems to be an issue to report.  Not sure if this is the right place to post.

**Comment by tianon** [comment] 2015-10-08 16:31
Man, you posted at almost the exact same time as #95 (which this is a dupe of). :+1:

**Closed by tianon** 2015-10-08 16:31 UTC
