### ISSUE TITLE
Intermittent failure to start `postgres:9.4` container with only `pg_ctl: could not start server` error

### ISSUE THREAD

**Issue by nnutter** [docker-library/postgres#153] opened 2016-05-11 21:39 UTC
_Note: I feel like this is probably an issue with `pg_ctl` but wanted to share the information here in case others have a similar experience trying to use the `postgres:9.4` container._

I only recently started using Docker so it's somewhat more likely I am making dumb mistakes.  When trying to start the `postgres:9.4` container I have been having ~20% failure rate and it appears to be because `pg_ctl -w start` is incorrectly deciding that the server failed to start.

Version info, logs, etc. are below.  I've manually entered the container using the `--entrypoint` option and then run `bash docker-entrypoint.sh --` to try and debug the failure.  It seems that the "[pg_ctl -w start](https://github.com/docker-library/postgres/blob/8e867c8ba0fc8fd347e43ae53ddeba8e67242a53/9.4/docker-entrypoint.sh#L49-L51)" sometimes thinks the server failed to start but that the server processes are in fact running and I can manually connect with `psql -U postgres` just fine.

I'm not using `docker-compose` nor do I have any permission errors as is common in several other reports of the container failing to start.

```
$ sudo docker run --publish=5432 --detach postgres:9.4
```

```
$ sudo docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64
```

```
$ sudo docker logs ef2cd0bb073e
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
creating template1 database in /var/lib/postgresql/data/base/1 ... ok
initializing pg_authid ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    postgres -D /var/lib/postgresql/data
or
    pg_ctl -D /var/lib/postgresql/data -l logfile start


WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
****************************************************
WARNING: No password has been set for the database.
         This will allow anyone with access to the
         Postgres port to access your database. In
         Docker's default configuration, this is
         effectively any other container on the same
         system.

         Use "-e POSTGRES_PASSWORD=password" to set
         it in "docker run".
****************************************************
waiting for server to start....LOG:  database system was shut down at 2016-05-11 19:48:40 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
........................................................... stopped waiting
pg_ctl: could not start server
Examine the log output.
```

**Comment by lfittl** [comment] 2016-05-11 21:50
@nnutter Not one of the maintainers, but curious if passing in a higher `PGCTLTIMEOUT`, e.g. as `-e PGCTLTIMEOUT=300` makes this go away?

**Comment by nnutter** [comment] 2016-05-11 23:35
@lfittl That was a great thought.  I tried setting it (confirmed with `docker inspect` and the time it took for the `pg_ctl` error to show up) but it did not prevent the issue.  I've tested mostly with `PGCTLTIMEOUT=30` but did some with `PGCTLTIMEOUT=300`.  When it works correctly it works consistently in about 6 seconds.

**Comment by nnutter** [comment] 2016-05-17 18:45
The occurrence of this problem is sporadic.  Some days I have trouble producing it and some days it happens over and over.  It is also worth noting that it has been observed on multiple machines with different accounts and environments.  I've worked around the issue by building `FROM postgres:9.4` with the following patch,

```diff
--- a/docker-entrypoint.sh      2016-05-13 10:33:51.108587454 -0500
+++ b/docker-entrypoint.sh      2016-05-13 10:51:30.596243343 -0500
@@ -48,7 +48,22 @@
                # does not listen on external TCP/IP and waits until start finishes
                gosu postgres pg_ctl -D "$PGDATA" \
                        -o "-c listen_addresses='localhost'" \
-                       -w start
+                       -w start || true
+
+               # workaround for `pg_ctl -w start` sometimes failing even though
+               # postgres is running
+               slept=0
+               echo -n >&2 "Waiting for postgres to start (workaround)"
+               until psql -U postgres -h localhost -c "select 1" >/dev/null 2>&1; do
+                       echo -n >&2 "."
+                       if [ $slept -ge 10 ]; then
+                               echo
+                               echo "Timed out waiting for postgres to start (workaround)"
+                               exit 1
+                       fi
+                       sleep 1
+                       slept=$[$slept + 1]
+               done

                : ${POSTGRES_USER:=postgres}
                : ${POSTGRES_DB:=$POSTGRES_USER}
```

I wish I could provide some understanding of what has been happening.

**Comment by tianon** [comment] 2018-06-08 20:15
This is a bit old now, so I'm guessing folks have moved on, but barring that I don't think there's much more we can do to help here -- this looks to be an extremely odd environmental issue.  We certainly can't reproduce it. :disappointed:

If there's an easy way we can reproduce the issue, we'd love to dig in so we can get it fixed (in the meantime, I'm going to close this out). :+1:

**Closed by tianon** 2018-06-08 20:15 UTC
Labels: Issue
