### ISSUE TITLE
Support sub-directories within docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by lloydpowell88** [docker-library/postgres#605] opened 2019-08-13 09:42 UTC
As it stands, the docker-entrypoint-initdb.d folder will only run the scripts from it's root.

I have a scenario where it would be extremely tidy for it to run  all scripts from directories placed in the root also (recursively would be nice too but probably not required).

This makes the managing of a multi-version application deployed in multiple environments much more simplistic. It allows us to group our scripts by folders making them more understandable, readable and easier to avoid the alphabetical ordering of all the scripts (this could be done by the grouping folders).

I can make this change easily enough myself and more than happy to create a pull request to see if others would find it beneficial also.

What do you think team?

**Comment by lloydpowell88** [comment] 2019-08-13 09:54
https://github.com/docker-library/postgres/pull/606

**Comment by yosifkit** [comment] 2019-08-13 23:03
> Maybe we just recommend users mount a script and have it run other scripts in their folders.

Duplicate of #179

I think we are still hesitant to have such a possibly breaking change (even more now with the long precedent of the current behavior).

So the current script users need to create would be a copy lines 145-163 to get the same behavior.
https://github.com/docker-library/postgres/blob/db452338a99764f0141aae60f7267a58f665e6b7/docker-entrypoint.sh#L145-L163

Hopefully #496 will be finished up soon and that should make it easier for the custom script.  Once merged the script would be roughly one line of code.

```bash
#!/bin/bash
# script will need to not be executable (chmod -x) so that it gets sourced rather than executed
# that is the current behavior, but this function doesn't exist yet
docker_process_init_files /docker-entrypoint-initdb.d/*/*
# or something else to better control the order of script and sql processing
```

**Comment by lloydpowell88** [comment] 2019-08-14 13:33
Thanks for the response @yosifkit .

That's a shame, breaking changes shouldn't always be considered a stopper from releasing a new feature! Especially in a case like this where people probably shouldn't really be putting folders in if they don't expect them to be used.

Maybe it could be reconsidered for the next major version :-), then those updating will know the potential of breaking changes when updating.

Thanks for sending through the potential alternative, I'll keep my eye on that change making it's way through.

**Comment by yosifkit** [comment] 2019-12-18 22:15
Closing since this is not something we want to add. 

Since scripts initdb scripts can be sourced (https://github.com/docker-library/postgres/pull/452) and everything in the script is functionalized (https://github.com/docker-library/postgres/pull/496), a custom script in initdb can easily use the `docker_process_init_files` function to recurse as deeply as desired.

Related issues https://github.com/docker-library/postgres/issues/179, https://github.com/docker-library/postgres/issues/605, https://github.com/docker-library/mysql/issues/192, https://github.com/docker-library/mysql/issues/193

**Closed by yosifkit** 2019-12-18 22:15 UTC
Labels: Request
