### ISSUE TITLE
Why can not run container by postgres 9.6 Dockerfile 

### ISSUE THREAD

**Issue by BBaek** [docker-library/postgres#347] opened 2017-09-25 10:39 UTC
I built new docker image with 9.6 Dockerfile and docker-entrypoint.sh.
$ docker build -t lqs_db_postgres .
![image](https://user-images.githubusercontent.com/6959474/30804602-00e06636-a229-11e7-9fdc-7deeee1d30bc.png)

But can not run(Exited (127)) docker container by new image.
$ docker run -it --name db -e POSTGRES_DB=lqs -e POSTGRES_USER=lqs -e POSTGRES_PASSWORD=a1234 -p 5432:5432 -d lqs_db_postgres
![image](https://user-images.githubusercontent.com/6959474/30804501-a5fee2a6-a228-11e7-904d-b8ce7e4768cb.png)

Is there a problem with the file(version 9.6)?

**Comment by tianon** [comment] 2017-09-26 00:35
I can't seem to reproduce: :confused: 
```console

$ docker pull postgres:9.6
9.6: Pulling from library/postgres
Digest: sha256:144221a1e46af653bdda2bbb8e46ad3dd0c3f61ec0430030581031937f1d589d
Status: Image is up to date for postgres:9.6

$ docker run -it --name db -e POSTGRES_DB=lqs -e POSTGRES_USER=lqs -e POSTGRES_PASSWORD=a1234 -p 5432:5432 -d postgres:9.6
a5c08b8ab6affb5a541df58625168b402f201dd5d184f3405f03592f40f9484c

$ docker ps --filter name=db
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
a5c08b8ab6af        postgres:9.6        "docker-entrypoint..."   27 seconds ago      Up 25 seconds       0.0.0.0:5432->5432/tcp   db

$ docker logs --tail 20 db

CREATE ROLE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

LOG:  received fast shutdown request
waiting for server to shut down...LOG:  aborting any active transactions
.LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2017-09-26 00:34:23 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started

$ 
```

**Comment by BBaek** [comment] 2017-09-26 01:05
Pulling image is no problem.
But I didn't download image file.

I download 2 files.
1. https://github.com/docker-library/postgres/blob/master/9.6/Dockerfile
2. https://github.com/docker-library/postgres/blob/master/9.6/docker-entrypoint.sh

And build it using 2files.

**Comment by yosifkit** [comment] 2017-09-26 17:53
Then that is the problem.  The file `docker-entrypoint.sh` file must be executable before you do docker build.  Duplicate of https://github.com/docker-library/postgres/issues/296; related issues https://github.com/docker-library/wordpress/issues/236, https://github.com/docker-library/ghost/pull/83, and https://github.com/docker-library/redis/pull/100.

**Closed by yosifkit** 2017-09-26 17:53 UTC
