### ISSUE TITLE
Ability to set fsync=off with environment variable

### ISSUE THREAD

**Issue by intellix** [docker-library/postgres#968] opened 2022-06-05 15:10 UTC
It would be a nice convenience if you could set fsync=off for when using this image in integration tests due to how much of a performance boost it gives (in my case it goes from 300sec -> 40sec) using an environment variable.

So instead of:
```yaml
db:
  image: postgres
  command: -c fsync=off
  environment:
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=blahblah
    - POSTGRES_DB=mydb
```

It would be possible to do:
```yaml
db:
  image: postgres
  environment:
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=blahblah
    - POSTGRES_DB=mydb
    - POSTGRES_FSYNC=off
```

I'd like to use `command: -c fsync=off` within my Gitlab CI/CD test step but you only really have access to the env vars for customisation. Currently my workaround is to use bitnami/postgresql which supports it

**Comment by yosifkit** [comment] 2022-06-08 22:58
Duplicate of https://github.com/docker-library/postgres/issues/831. In general, we are unlikely to add more environment variables;  specifically, we are not going to add a variable for anything that can be done via an argument to the `postgres` server binary.

**Closed by yosifkit** 2022-06-08 22:58 UTC
Labels: Request

**Comment by simplenotezy** [comment] 2022-06-20 00:54
@yosifkit Using github actions or docker-compose, can you provide an example of how to disable fsync?

**Comment by simplenotezy** [comment] 2022-06-20 00:56
Found: https://github.com/docker-library/postgres/issues/149 for docker-compose - still curious about github actions
