### ISSUE TITLE
run postgres:9.5 got permission denined error

### ISSUE THREAD

**Issue by biaji** [docker-library/postgres#843] opened 2021-05-18 08:19 UTC
CentOS 7
Docker version 1.13.1, build 7d71120/1.13.1

```
# docker pull postgres:9.5
# docker run -it --rm  --name sentry-postgres --env POSTGRES_PASSWORD=somepasswd postgres:9.5
```

and got:

`find: ‘/var/run/postgresql’: Permission denied`

if I add --user:

```
docker run -it --rm  --user 1001 --name sentry-postgres --env POSTGRES_PASSWORD=somepasswd postgres:9.5
chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted
chmod: changing permissions of '/var/run/postgresql': Operation not permitted
ls: cannot open directory '/docker-entrypoint-initdb.d/': Permission denied
```

uid 999 is :
`polkitd:x:999:997:User for polkitd:/:/sbin/nologin`

I'm not sure what happened.  I'll check it then append what I find here.

**Comment by wglambert** [comment] 2021-05-18 16:14
Could be SELinux https://github.com/docker-library/mysql/issues/198
But otherwise it seems related to the host's environment or filesystem permissions since I'm unable to reproduce

```console
$ docker run -it --rm  --name sentry-postgres --env POSTGRES_PASSWORD=somepasswd postgres:9.5
Unable to find image 'postgres:9.5' locally
9.5: Pulling from library/postgres
fa1690ae9228: Pull complete 
a73f6e07b158: Pull complete 
973a0c44ddba: Pull complete 
07e5342b01d4: Pull complete 
578aad0862c9: Pull complete 
a0b157088f7a: Pull complete 
6c9046f06fc5: Pull complete 
ae19407bdc48: Pull complete 
e53b7c20aa96: Pull complete 
a135edcc0831: Pull complete 
fed07b1b1b94: Pull complete 
18d9026fcfbd: Pull complete 
4d2d5fae97d9: Pull complete 
d419466e642d: Pull complete 
Digest: sha256:75ebf479151a8fd77bf2fed46ef76ce8d518c23264734c48f2d1de42b4eb40ae
Status: Downloaded newer image for postgres:9.5
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
creating template1 database in /var/lib/postgresql/data/base/1 ... ok
initializing pg_authid ... ok
setting password ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....LOG:  database system was shut down at 2021-05-18 16:13:02 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
 done
server started

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2021-05-18 16:13:04 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
```

**Comment by biaji** [comment] 2021-05-19 09:34
@wglambert Thanks for your verify. I'll check the env and filesystem permission.  

I deploy another machine and it goes smooth.  Which make this situation more wired.

**Comment by whizyrel** [comment] 2021-06-07 13:05
If this issue is solved, could you please close it @biaji 😄 ? Thank you

**Closed** 2021-06-07 19:23 UTC
Labels: question
