### ISSUE TITLE
docker-entrypoint.sh permission denied

### ISSUE THREAD

**Issue by Erowlin** [docker-library/postgres#21] opened 2014-09-16 12:58 UTC
I have a problem launching the container : 
2014/09/16 08:56:36 Error response from daemon: Cannot start container 19c947b7844207f0e41e1ed6a6ec130cb0659667a53cf29ad98cde68b0cd5c6e: exec: "/docker-entrypoint.sh": permission denied

Here some output : 
root@db:~# ls
docker-entrypoint.sh  Dockerfile  start.sh

to build the image : 
docker build -t postgres .

to run the image : 
docker run -t -i -p 5432:5432 --name postgresql -d postgres /bin/bash

**Comment by yosifkit** [comment] 2015-01-23 00:04
Unable to reproduce. Closing. (feel free to post if more information is found to reproduce)

**Closed by yosifkit** 2015-01-23 00:04 UTC

**Comment by tianon** [comment] 2018-01-09 17:48
@asevans48 as @yosifkit pointed out above (no less than 3 years ago now), we cannot reproduce a failure:

```console

$ docker pull postgres
Using default tag: latest
latest: Pulling from library/postgres
Digest: sha256:3f4441460029e12905a5d447a3549ae2ac13323d045391b0cb0cf8b48ea17463
Status: Downloaded newer image for postgres:latest

$ docker run -it --rm --cpus 2 -p 5432:5432 -e POSTGRES_PASSWORD='xxx' -e POSTGRES_USER='yyy' postgres
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2018-01-09 17:48:38.390 UTC [39] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2018-01-09 17:48:38.390 UTC [39] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2018-01-09 17:48:38.390 UTC [39] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2018-01-09 17:48:38.392 UTC [39] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2018-01-09 17:48:38.400 UTC [40] LOG:  database system was shut down at 2018-01-09 17:48:38 UTC
2018-01-09 17:48:38.403 UTC [39] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE

CREATE ROLE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2018-01-09 17:48:38.895 UTC [39] LOG:  received fast shutdown request
waiting for server to shut down....2018-01-09 17:48:38.897 UTC [39] LOG:  aborting any active transactions
2018-01-09 17:48:38.898 UTC [39] LOG:  worker process: logical replication launcher (PID 46) exited with exit code 1
2018-01-09 17:48:38.898 UTC [41] LOG:  shutting down
2018-01-09 17:48:38.911 UTC [39] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2018-01-09 17:48:39.023 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2018-01-09 17:48:39.023 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2018-01-09 17:48:39.026 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2018-01-09 17:48:39.041 UTC [66] LOG:  database system was shut down at 2018-01-09 17:48:38 UTC
2018-01-09 17:48:39.045 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by liadmagen** [comment] 2020-06-08 14:39
If anyone encounter this problem, please consider updating or reinstalling docker on your machine.
