### ISSUE TITLE
Updating data from 9.5 to 9.6

### ISSUE THREAD

**Issue by kingbuzzman** [docker-library/postgres#339] opened 2017-09-15 18:50 UTC
How do i upgrade the data from the old docker postgres:9.5-alpine to postgres:9.6-alpine?

I tried running `pg_upgrade` but im getting permission issues, when i do `su postgres` then run it. I get more issues. Anyone got it to work?

**Comment by tianon** [comment] 2017-09-15 18:57
This is a duplicate of https://github.com/docker-library/postgres/issues/37, which has a lot of really great discussion on this topic. :+1:

**Closed by tianon** 2017-09-15 18:57 UTC
