### ISSUE TITLE
Handle data migration in docker-entrypoint.sh

### ISSUE THREAD

**Issue by codeReader52** [docker-library/postgres#712] opened 2020-04-13 00:06 UTC
Hi docker postgres experts,
I was wondering if it's worth to expose a way to execute a bash script every time the container spins up after executing the current logic in `docker-entrypoint.sh` script. The example usage could be for data-migration. The desired execution would be along the line of:
1. Execute current logic in `docker-entrypoint.sh`
2. Additional logic to perform data migration:
      If database version is 1, then perform `migration 1`, `migration 2`, `migration 3`
      Else if database version is 2, then perform `migration 2`, `migration 3`
      Else if database version is 3, then perform `migration 3`
      Else do nothing

Step 2 can probably be executed by a bash script. Hence, in general, I think it's worth it to expose a way to specify a bash script every time the container spins up rather than just initialisation logic in folder `docker-entrypoint-initdb.d`. Currently, the scripts in `docker-entrypoint-initdb.d` only gets executed if the file `$PGDATA/PG_VERSION` doesn't exists or has size 0. Meaning that if a database already exists, there is no way to perform any data-migration (that I know of).
 
Propose: we could specify another folder such as `docker-data-migration.d` similar to `docker-entrypoint-initdb.d` but any bash scripts in it will get run every time the container spins up.

**Comment by phi1010** [comment] 2021-08-01 17:01
I am currently using a derived Dockerfile which patches the original code:

```
RUN sed '/PostgreSQL Database directory appears to contain a database; Skipping initialization/{q42}' ./docker-entrypoint.sh >/dev/null; \
    test $? -eq 42 || ("Failed to patch docker-entrypoint.sh to add a pre-start-script"; exit 1)

# And insert a call to run-parts -- this will run files in /docker-entrypoint-restartdb.d/ whenever the server is restarted after first initialization.
RUN sed -i '/PostgreSQL Database directory appears to contain a database; Skipping initialization/adocker_temp_server_start "$@" ; run-parts --report docker-entrypoint-restartdb.d ; docker_temp_server_stop' ./docker-entrypoint.sh
RUN tail -n20 ./docker-entrypoint.sh
```

I think managing migrations in the docker image itself based on datavase versions would be an unecessary bloat, but it would be nice to have a some hooks to call such additional features from, without the risk of such hacky text replacements failing on update.

Dear maintainers, would a pull request for such an extension of the entrypoint be welcome?

I am thinking of:

* A second directory for scripts run on every startup of the server (probably without run-parts, using the existing sourcing mechanism for consistency instead)
    * This one can be used to add a custom migration mechanism for users, passwords, databases and data here.
* A script to set the database password from the environment variable on every startup, not just the first one
* A wrapper that can be used to execute a script / command, and then stop the server and container
    * This one can be used to enable admins' scripts to e.g. invoke an sql command via psql from outside, without race conditions on server startup.
* Maybe: Fixing the entrypoint script to no longer use undefined variables.

**Comment by yosifkit** [comment] 2021-08-02 17:27
This is basically the example I used when we functionalized the entrypoint script and the way we support this type of extended functionality.  We are not going to further increase the complexity of the already very complex entrypoint script. There is no need to edit the entrypoint, just extend it.

From https://github.com/docker-library/postgres/pull/496#issue-214478296:

> Here is an example using the current interface to run other init scripts on every start:
> ```bash
> #!/usr/bin/env bash
> set -Eeo pipefail
> 
> # Example using the functions of the postgres entrypoint to customize startup to always run files in /always-initdb.d/
> 
> source "$(which docker-entrypoint.sh)"
> 
> docker_setup_env
> docker_create_db_directories
> # assumption: we are already running as the owner of PGDATA
> 
> # This is needed if the container is started as `root`
> #if [ "$1" = 'postgres' ] && [ "$(id -u)" = '0' ]; then
> #	exec gosu postgres "$BASH_SOURCE" "$@"
> #fi
> 
> if [ -z "$DATABASE_ALREADY_EXISTS" ]; then
> 	docker_verify_minimum_env
> 	docker_init_database_dir
> 	pg_setup_hba_conf
> 	
> 	# only required for '--auth[-local]=md5' on POSTGRES_INITDB_ARGS
> 	export PGPASSWORD="${PGPASSWORD:-$POSTGRES_PASSWORD}"
> 	
> 	docker_temp_server_start "$@" -c max_locks_per_transaction=256
> 	docker_setup_db
> 	docker_process_init_files /docker-entrypoint-initdb.d/*
> 	docker_temp_server_stop
> else
> 	docker_temp_server_start "$@"
> 	docker_process_init_files /always-initdb.d/*
> 	docker_temp_server_stop
> fi
> 
> exec postgres "$@"
> ```
> 
> ```console
> $ docker run -it --rm \
>   -e POSTGRES_PASSWORD=12345 \
>   -v "$PWD/custom-entrypoint.sh":/usr/local/bin/custom-entrypoint.sh \
>   -v "$PWD/docker-entrypoint-initdb.d/":/docker-entrypoint-initdb.d/ \
>   -v "$PWD/always-initdb.d/":/always-initdb.d/ \
>   -v "$PWD/data/":/var/lib/postgresql/data/ \
>   --name=pg --user=1000 \
>   postgres:11-test custom-entrypoint.sh -c 'max_locks_per_transaction=512'
> ```

While I didn't build an image with the entrypoint custom script, that would be the recommended way to do it. It still works since the entrypoint functions are meant to be unchanged in their interface and use (the functions that start with underscore are meant to be "private" and could change in the future).

Duplicate of https://github.com/docker-library/postgres/issues/821, https://github.com/docker-library/postgres/issues/191, https://github.com/docker-library/postgres/issues/542

**Closed by yosifkit** 2021-08-02 17:27 UTC
Labels: Request

**Comment by phi1010** [comment] 2021-08-07 17:49
This looks good, and would solve these kinds of issues, but does not seem to be included in current releases ( https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh#L307 ) 

```sh
~$ docker run postgres grep 'always' /docker-entrypoint.sh
#    ie: docker_process_init_files /always-initdb.d/*
                        # leaving out -C on purpose since it always fails and is unhelpful:

```
