### ISSUE TITLE
Run database initialization after startup

### ISSUE THREAD

**Issue by benno-mueller-saxess** [docker-library/postgres#1196] opened 2024-02-14 19:21 UTC
I want to run some database initialization script after the server has startet successfull (Log: "LOG:  Datenbanksystem ist bereit, um Verbindungen anzunehmen"). I'm using currently image postgres:12.18

How can I do this with an Dockerfile?

**Comment by tianon** [comment] 2024-02-14 19:33
See https://github.com/docker-library/postgres/issues/173, https://github.com/docker-library/postgres/issues/821, https://github.com/docker-library/postgres/issues/191, https://github.com/docker-library/postgres/issues/929 for some other issues that have some good thoughts / suggestions (one of/many of which this is probably a solid duplicate of).

**Closed** 2024-03-14 17:22 UTC
