### ISSUE TITLE
Add option to not start the database after run init_db

### ISSUE THREAD

**Issue by cath222ou** [docker-library/postgres#1001] opened 2022-10-03 17:03 UTC
It is possible to add an option to not start the database after running docker-entrypoint.sh. I would like my container to stop after running some scripts in the temporary database.

![image](https://user-images.githubusercontent.com/30536406/193636304-7ece0eb3-4204-4863-bcfa-8470683ab608.png)

**Comment by tianon** [comment] 2022-10-03 22:05
Duplicate of #424

**Closed by tianon** 2022-10-03 22:05 UTC
