### ISSUE TITLE
Volume will created always, also when it doesn't need

### ISSUE THREAD

**Issue by rnz** [docker-library/postgres#566] opened 2019-04-04 09:47 UTC
https://github.com/docker-library/postgres/blob/7e80419825e4bab4e749bc61334570ffc261ea5e/11/Dockerfile#L168

When create multiple container with bind data directory for postgres, docker create volume if use this image based on this Dockerfile
Please add check ENV condition for create or not create volume.

same for other postgresql version

**Comment by wglambert** [comment] 2019-04-04 16:18
Duplicate of https://github.com/docker-library/postgres/issues/404

**Closed by wglambert** 2019-04-04 16:18 UTC
