### ISSUE TITLE
Postgres:10 is not pulled

### ISSUE THREAD

**Issue by borismu** [docker-library/postgres#813] opened 2021-02-03 19:00 UTC
`10: Pulling from library/postgres
no matching manifest for linux/amd64 in the manifest list entries`

![Screenshot from 2021-02-03 20-59-37](https://user-images.githubusercontent.com/4933610/106795455-c4d42e00-6662-11eb-9e70-745ed1b321af.png)

> (base) ➜  ~ docker pull postgres:10
> 10: Pulling from library/postgres
> no matching manifest for linux/amd64 in the manifest list entries
> (base) ➜  ~ docker pull postgres:10.15
> 10.15: Pulling from library/postgres
> Digest: sha256:c0b70dc6d73a22d6a48b72d04dbd5454e1f5eb0b186c083e5bbbf4d16d9c4670
> Status: Image is up to date for postgres:10.15
> docker.io/library/postgres:10.15

**Comment by phemmer** [comment] 2021-02-03 19:03
The image is missing the `amd64` tag. Looks like this is not unique to the postgres image either: https://github.com/docker-library/official-images/issues/9562

**Comment by ChuckBates** [comment] 2021-02-03 19:03
I also just started getting "no matching manifest for linux/amd64" errors. For me it was pulling 10-alpine.  I think it has to do with the latest tag update: 
![image](https://user-images.githubusercontent.com/8691839/106795848-db08cc80-6617-11eb-9b88-af4342138c23.png)

**Comment by tianon** [comment] 2021-02-03 19:04
Ugh, this is probably related to / caused by the recent outage: https://status.docker.com/pages/history/533c6539221ae15e3f000031

**Comment by tianon** [comment] 2021-02-03 19:05
Both `postgres:10` and `postgres:10-alpine` should be fixed now.

**Comment by glours** [comment] 2021-02-03 19:06
Yes I confirm, I just pulled the `postgres:10` image
Thanks @tianon

**Closed** 2021-02-03 19:06 UTC
