### ISSUE TITLE
Add optional POSTGRES_PORT environment variable 

### ISSUE THREAD

**Issue by kingsleytorlowei** [docker-library/postgres#1000] opened 2022-09-22 17:38 UTC
I'm currently using the Postgres docker executor on GitLab CI and I want to set the POSTGRES_PORT environment variable to whatever I want. How can I do that? POSTGRES_PORT doesn't seem like a valid variable right now

**Comment by wglambert** [comment] 2022-09-22 18:05
Duplicate of https://github.com/docker-library/postgres/issues/702

**Closed** 2022-09-22 23:11 UTC
Labels: Request
