### ISSUE TITLE
could not fork autovacuum worker process: Cannot allocate memory

### ISSUE THREAD

**Issue by AnatoleAnacrouse** [docker-library/postgres#508] opened 2018-10-03 20:39 UTC
Running on Windows Postgres DB linked to lequal/docker-cat using the docker-cat/docker-compose.yml  (see https://github.com/lequal/docker-cat/blob/master/docker-compose.yml) provided by Lequal (see issue https://github.com/lequal/docker-cat/issues/4).

Docker-cat is running pretty well but using postgres DB loops with the following error log message : "could not fork autovacuum worker process: Cannot allocate memory" and  lequal/docker-cat crashes with Java exception.

**Comment by wglambert** [comment] 2018-10-03 20:50
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

From your error it could be either resource exhaustion or hardware related. Related issues:
https://dba.stackexchange.com/questions/116027/postgresql-could-not-fork-autovacuum-worker-process-cannot-allocate-memory
http://postgresdesk.blogspot.com/2015/08/postgresql-could-not-fork-autovacuum.html
https://meta.discourse.org/t/could-not-fork-autovacuum-worker-process/49796

**Comment by tianon** [comment] 2018-10-03 20:51
Yeah, this definitely sounds like your system doesn't have enough memory.  If you're on Docker for Windows, you probably want to increase the amount of memory allocated to the Docker VM.

Closing, since this doesn't appear to be an issue with the image (and is really environmental).

**Closed by tianon** 2018-10-03 20:51 UTC
Labels: question

**Comment by AnatoleAnacrouse** [comment] 2018-10-04 18:05
I have increased the memory allocated to virtualbox and the pb is resolved.
Thanx  for your precious help.

Anatole
