### ISSUE TITLE
Set timezone in Postgres Docker Image

### ISSUE THREAD

**Issue by pedrofurtado** [docker-library/postgres#458] opened 2018-06-09 19:48 UTC
My application uses `America\Sao_Paulo` timezone. How do I set the timezone in my Dockerfile of Postgres 10.4 docker image? Do I need to add a ENV command ?

**Comment by wglambert** [comment] 2018-06-11 17:34
Duplicate of https://github.com/docker-library/ruby/issues/218

**Closed by wglambert** 2018-06-11 17:34 UTC

**Comment by yosifkit** [comment] 2018-06-11 23:37
Duplicate of https://github.com/docker-library/postgres/issues/137
