### ISSUE TITLE
| ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted

### ISSUE THREAD

**Issue by ponmanikandanb** [docker-library/postgres#890] opened 2021-09-29 17:56 UTC
getting the below error in the latest postgres docker image.

**| ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted**

after i pointed to older version its working fine.

My docker file as below.

```
ARG DB_BASE_IMAGE
FROM ${DB_BASE_IMAGE}

ADD initdb.sql /docker-entrypoint-initdb.d/
```

**Comment by wglambert** [comment] 2021-09-29 18:26
Duplicate of https://github.com/docker-library/postgres/issues/884#issuecomment-926855364
>you'll need to update Docker, runc, and likely libseccomp on your host.

**Closed by wglambert** 2021-09-29 18:26 UTC

**Comment by ghosesuvendu** [comment] 2024-09-29 09:57
I was facing a similar exception with Docker version 18.09.1-ol, build e32a1bd. However, when I tried the same setup on the upgraded Docker version 20.10.9, build c2ea9bc on Red Hat Enterprise Linux Server 7.3 (Maipo) (CPE OS Name: cpe:/o:redhat:enterprise_linux:7.3:GA:server), the issue was resolved.
