### ISSUE TITLE
DB changes by /docker-entrypoint-initdb.d/*.sh not saved

### ISSUE THREAD

**Issue by The-Judge** [docker-library/postgres#522] opened 2018-11-05 14:57 UTC
Hi there,

when launching your image `postgres:10-alpine` with a script in `/docker-entrypoint-initdb.d/*.sh`, that seems to be applied. It looks like this:

```
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER micm;
    CREATE DATABASE micm;
    GRANT ALL PRIVILEGES ON DATABASE micm TO micm;
EOSQL

zcat "/docker-entrypoint-initdb.d/cmdb.dump.gz" | psql -v -U "${POSTGRES_USER}" micm
```

Logging in to that PostgreSQL image shows that the user and database named `micm` exists, but is empty:

```
$ docker-enter cmdb
/ # psql -U postgres micm
psql (10.5)
Type "help" for help.

micm=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
-----------+----------+----------+------------+------------+-----------------------
 micm      | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/postgres         +
           |          |          |            |            | postgres=CTc/postgres+
           |          |          |            |            | micm=CTc/postgres
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(4 rows)

micm=# \dt
Did not find any relations.
micm=# \q
/ #
```

When I apply that very same dump manually once more, the DB is filled:
```
/ # zcat /docker-entrypoint-initdb.d/cmdb.dump.gz | psql -U postgres micm
SET
SET
SET
...
/ # echo $?
0
/ # psql -U postgres micm
psql (10.5)
Type "help" for help.

micm=# \dt
                              List of relations
 Schema |                       Name                       | Type  |  Owner   
--------+--------------------------------------------------+-------+----------
 public | datacenter                                       | table | micm_adm
 public | device                                           | table | micm_adm
...
```

Am I missing something here or is this a bug?

**Comment by The-Judge** [comment] 2018-11-05 15:03
PS: Somehow, creating the database like `CREATE DATABASE micm WITH OWNER micm;` and applying the dump as this user works.

**Comment by wglambert** [comment] 2018-11-05 21:13
Using the [environment variables](https://github.com/docker-library/postgres/blob/master/10/docker-entrypoint.sh) would also handle user creation and database owner

```console
$ docker run --rm -dit -e POSTGRES_USER=micm --name postgres postgres:10-alpine
$ docker exec -it postgres sh
/ # psql -U micm
psql (10.5)
Type "help" for help.

micm=# \l
                             List of databases
   Name    | Owner | Encoding |  Collate   |   Ctype    | Access privileges 
-----------+-------+----------+------------+------------+-------------------
 micm      | micm  | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres  | micm  | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0 | micm  | UTF8     | en_US.utf8 | en_US.utf8 | =c/micm          +
           |       |          |            |            | micm=CTc/micm
 template1 | micm  | UTF8     | en_US.utf8 | en_US.utf8 | =c/micm          +
           |       |          |            |            | micm=CTc/micm
(4 rows)
```

Closing since the issue is resolved

**Closed by wglambert** 2018-11-05 21:13 UTC
Labels: question
