### ISSUE TITLE
Missing 10.22 and 11.17 image tags

### ISSUE THREAD

**Issue by edwardsamuel** [docker-library/postgres#997] opened 2022-09-16 03:04 UTC
In the latest image release, I could only see `10.22-<os_variant>` and `11.17-<os_variant>` tags, but there were no `10.22` and `11.17` tags. Was this expected? If not, could we add the `10.22` and `11.17` tags?

**Comment by yosifkit** [comment] 2022-09-16 16:13
> Versions `10` and `11` do not have any plain tags; See https://github.com/docker-library/postgres/issues/582

Duplicate of https://github.com/docker-library/postgres/issues/996

**Closed** 2022-09-16 18:15 UTC
