### ISSUE TITLE
ERROR:  invalid locale name: "English_United States" on Postgres 9.6 K8S 

### ISSUE THREAD

**Issue by henri9813** [docker-library/postgres#719] opened 2020-04-20 21:27 UTC
Hello,

I have this error for PostgreSQL 9.6 on a kubernetes cluster:
``` 
LOG:  database system was shut down at 2020-04-20 21:25:08 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
LOG:  incomplete startup packet
FATAL:  database "fusionauth" does not exist
LOG:  incomplete startup packet
FATAL:  database "fusionauth" does not exist
LOG:  incomplete startup packet
ERROR:  duplicate key value violates unique constraint "pg_database_datname_index"
DETAIL:  Key (datname)=(fusionauth) already exists.
STATEMENT:  CREATE DATABASE fusionauth ENCODING 'UTF-8' LC_CTYPE 'en_US.UTF-8' LC_COLLATE 'en_US.UTF-8' TEMPLATE template0
ERROR:  invalid locale name: "English_United States"
STATEMENT:  CREATE DATABASE fusionauth ENCODING 'UTF-8' LC_CTYPE 'English_United States' LC_COLLATE 'English_United States' TEMPLATE template0
LOG:  incomplete startup packet
ERROR:  relation "version" does not exist at character 21
STATEMENT:  select version from version
LOG:  incomplete startup packet
LOG:  incomplete startup packet
``` 

Do you have an idea to how can i fix it ?  Or maybe a workaround ?

**Comment by wglambert** [comment] 2020-04-20 21:57
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

Are you using a helm chart?

**Comment by henri9813** [comment] 2020-04-21 06:47
Hello

No i don't use helm chart, i create my own deployment

``` 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:9.6
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: db
              protocol: TCP
```

May should i had some environment values for this ?

**Comment by henri9813** [comment] 2020-04-21 07:22
My problem seems to have been solved, it seems to be a fusionauth issue
https://github.com/FusionAuth/fusionauth-issues/issues/567

**Comment by wglambert** [comment] 2020-04-21 14:50
Cool, closing since this is resolved then

**Closed by wglambert** 2020-04-21 14:50 UTC
