### ISSUE TITLE
Any postgresql 13.x ARMHL image crashes with segfault 

### ISSUE THREAD

**Issue by agilob** [docker-library/postgres#836] opened 2021-04-21 10:22 UTC
```
pi@rpi1:~ $ docker-compose -f postgres-compose.yaml up
Starting postgresql ... done
Attaching to postgresql
postgresql    | The files belonging to this database system will be owned by user "postgres".
postgresql    | This user must also own the server process.
postgresql    |
postgresql    | The database cluster will be initialized with locale "en_US.utf8".
postgresql    | The default database encoding has accordingly been set to "UTF8".
postgresql    | The default text search configuration will be set to "english".
postgresql    |
postgresql    | Data page checksums are disabled.
postgresql    |
postgresql    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgresql    | creating subdirectories ... ok
postgresql    | selecting dynamic shared memory implementation ... posix
postgresql    | selecting default max_connections ... 100
postgresql    | selecting default shared_buffers ... 128MB
postgresql    | selecting default time zone ... GMT
postgresql    | creating configuration files ... ok
postgresql    | running bootstrap script ... ok
postgresql    | performing post-bootstrap initialization ... sh: locale: not found
postgresql    | 1970-05-17 17:01:28.011 GMT [31] WARNING:  no usable system locales were found
postgresql    | ok
postgresql    | syncing data to disk ... ok
postgresql    |
postgresql    |
postgresql    | Success. You can now start the database server using:
postgresql    |
postgresql    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgresql    |
postgresql    | initdb: warning: enabling "trust" authentication for local connections
postgresql    | You can change this by editing pg_hba.conf or using the option -A, or
postgresql    | --auth-local and --auth-host, the next time you run initdb.
postgresql    | waiting for server to start....1970-05-19 23:38:16.011 GMT [36] LOG:  starting PostgreSQL 13.2 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
postgresql    | 1970-05-19 23:38:16.011 GMT [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql    | ...........1970-05-19 23:38:16.011 GMT [36] LOG:  startup process (PID 37) was terminated by signal 11: Segmentation fault
postgresql    | 1970-05-19 23:38:16.011 GMT [36] LOG:  aborting startup due to startup process failure
postgresql    | 1970-05-19 23:38:16.011 GMT [36] LOG:  database system is shut down
postgresql    |  stopped waiting
postgresql    | pg_ctl: could not start server
postgresql    | Examine the log output.
postgresql exited with code 1
```

Using this docker-compose:

```
version: "3.3"

services:
  postgresql:
    image: postgres:13.2-alpine
    container_name: postgresql
    hostname: postgres
    volumes:
      - $HOME/dockers/pg/data:/var/lib/postgresql/data:rw
      - $PWD/pg:/etc/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
    ports:
      - 5432:5432
```

i've tried ubuntu and alpine images, but they all crash. 12.4 works fine.

`Linux rpi1 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l GNU/Linux`

**Comment by agilob** [comment] 2021-04-21 12:44
12.6 is crashing too

**Comment by tianon** [comment] 2021-04-21 18:48
Which version of Docker are you running?  (It's very possible you're getting the armv7 images for your armv6 system.)

I'd suggest trying `arm32v6/postgres:13.2-alpine` explicitly, and if that fixes your issue then you probably want to update to Docker 20.10+ (and containerd 1.4+), but if it doesn't then it might be #812 (in which case you need to make sure your `libseccomp` is 2.4.2 or newer) or #830 (which has an indeterminate root case ATM).

**Comment by agilob** [comment] 2021-04-21 19:42
I tried `arm32v6/postgres:13.2-alpine`, but still the same problem:


```
postgresql    | Success. You can now start the database server using:
postgresql    | 
postgresql    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgresql    | 
postgresql    | initdb: warning: enabling "trust" authentication for local connections
postgresql    | You can change this by editing pg_hba.conf or using the option -A, or
postgresql    | --auth-local and --auth-host, the next time you run initdb.
postgresql    | waiting for server to start....1970-05-23 18:39:36.012 GMT [37] LOG:  starting PostgreSQL 13.2 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
postgresql    | 1970-05-23 18:39:36.012 GMT [37] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql    | ......1970-05-23 18:39:36.012 GMT [37] LOG:  startup process (PID 38) was terminated by signal 11: Segmentation fault
postgresql    | 1970-05-23 18:39:36.012 GMT [37] LOG:  aborting startup due to startup process failure
postgresql    | .1970-05-23 18:39:36.012 GMT [37] LOG:  database system is shut down
postgresql    |  stopped waiting
postgresql    | pg_ctl: could not start server
postgresql    | Examine the log output.
```

My docker version:
```
pi@rpi1:~ $ docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:18 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:17 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

I think it's the same as 812. Do I get it correctly that raspbian has old version of libseccomp so it provides incorrect timestamps to docker-ce which then passes it to containers?

**Comment by tianon** [comment] 2021-04-21 19:53
It's a little bit more complicated than that, but the gist is that your libseccomp is too old, so your containers don't get access to the time64 syscalls they're trying to use, and they all return `EPERM` (instead of `ENOSYS`, which they would use as a signal to fall back to time32 syscalls).

So the tl;dr is that you can either figure out some way to get a newer libseccomp on your raspbian (by updating to the not-yet-release bullseye, for example), or use something like `--security-opt seccomp=unconfined` to disable Docker's seccomp functionality (which isn't recommended, since it's a security feature designed to protect you).

Closing as a duplicate of #812.

**Closed by tianon** 2021-04-21 19:53 UTC
