### ISSUE TITLE
14.3 image on Docker Hub

### ISSUE THREAD

**Issue by dtcooper** [docker-library/postgres#959] opened 2022-05-17 22:29 UTC
Hi there,

Since version 14.3 was released on May 12, 2022 — I'm wondering when/if the release will make it on docker hub.

Link: <https://hub.docker.com/_/postgres> (latest version is 14.2)

Thank you,

David

**Comment by yosifkit** [comment] 2022-05-17 22:32
https://github.com/docker-library/postgres/tree/780680ebfa85d8220627985c0a16ecfd79d44a0f#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

**Comment by tianon** [comment] 2022-05-18 01:01
Duplicate of #958

**Closed by tianon** 2022-05-18 01:01 UTC
